name: planner
description: PegahSystem co.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 3.0.0+3

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  bot_toast: ^4.0.3
  appmetrica_plugin: ^1.1.0
  appmetrica_push_plugin: ^0.2.0
  push: ^0.1.3
  flutter_local_notifications: ^13.0.0
  timezone: ^0.9.1
  iconsax: ^0.0.8
  url_launcher: ^6.1.10
  shamsi_date: ^1.0.1
  hijri: ^3.0.0
  flutter_swipe_action_cell: ^3.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14
  persian_tools: ^1.0.3
  flutter_native_timezone: ^2.0.0
  sliver_tools: ^0.2.9
  syncfusion_flutter_charts: ^21.1.38
  # samsung_ui_scroll_effect: ^0.0.3

  # floating_bottom_bar: ^0.0.1

dev_dependencies:
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/img/
    - asset/img/noteCat/

  fonts:
    - family: iran
      fonts:
        - asset: asset/font/iransans.ttf
    - family: nast
      fonts:
        - asset: asset/font/IranNastaliq.ttf
